import type { Metadata } from "next";
import { PT_Serif, PT_Mono, Noto_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const PtSerifText = PT_Serif({
  variable: "--font-pt-serif",
  subsets: ["latin"],
  weight: ["400", "700"]
});

const ptMonoText = PT_Mono({
  variable: "--font-pt-mono",
  subsets: ["latin"],
  weight: ["400"]
});

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${PtSerifText.variable} ${ptMonoText.variable} ${notoSans.variable} antialiased`}
    >
      <body className="font-sans">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
